baseURL = "https://www.harlanhutton.com"
languageCode = "en-us"
title = "Harlan Hutton"
theme = "monopriv"

[params]
about = "Incoming Software Engineer at Google. Guest Researcher at the Flatiron Institute Center for Computational Astrophysics. M.S. in Data Science Student at NYU." 
github = "https://github.com/harlanhutton"
email = "ahh303@nyu.edu"
linkedin = "https://www.linkedin.com/in/harlanhutton/"

[params.hero]
enabled = true
img = "img/img.png"

